acceptance_tests:
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
  spec:
    tests:
      - spec_path: integration_tests/spec.json
connector_image: airbyte/source-azure-blob-storage:dev
test_strictness_level: low
